openapi: 3.0.3
info:
  title: Booking API v1.0
  description: REST API for a booking system
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Local server
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        service:
          type: string
          example: "Massage"
        start_time:
          type: string
          format: date-time
          example: "2025-10-25T10:00:00Z"
        end_time:
          type: string
          format: date-time
          example: "2025-10-25T11:00:00Z"
        status:
          type: string
          enum: [pending, confirmed, cancelled]
          example: "pending"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
paths:
  /bookings:
    get:
      summary: Get all bookings
      tags:
        - Bookings
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
    post:
      summary: Create a new booking
      tags:
        - Bookings
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - service
                - start_time
                - end_time
              properties:
                service:
                  type: string
                  example: "Massage"
                start_time:
                  type: string
                  format: date-time
                  example: "2025-10-25T10:00:00Z"
                end_time:
                  type: string
                  format: date-time
                  example: "2025-10-25T11:00:00Z"
      responses:
        '201':
          description: Booking created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
  /bookings/{id}:
    get:
      summary: Get a booking by ID
      tags:
        - Bookings
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Booking details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found
    put:
      summary: Update a booking
      tags:
        - Bookings
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                service:
                  type: string
                start_time:
                  type: string
                  format: date-time
                end_time:
                  type: string
                  format: date-time
                status:
                  type: string
                  enum: [pending, confirmed, cancelled]
      responses:
        '200':
          description: Updated booking
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found
    delete:
      summary: Delete a booking
      tags:
        - Bookings
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Booking deleted
        '404':
          description: Booking not found
